Sort resources by name
geoffreylgv/LearningHub pull request #25
Opened 2023-09-09 15:35 UTC by milkiyd

Hello, I added a python script that will automatically sort resource files links. After inserting new material links, you can just run the script and the file will be sorted.
I'm open to any remarks and changes if needed.

2023-09-11 17:40 UTC, geoffreylgv reviewed
Hi @milkiyd, did you use python code to sort automatically all links in the files?
(I mean I'm seeing it, but just to confirm)

2023-09-11 20:07 UTC, geoffreylgv requested changes
Here we have the learning resource starting by `S` but, still stay on the bottom.

2023-09-11 20:23 UTC, geoffreylgv reviewed
Hi @milkiyd Sorry for the delay, I was and still working on a project `(simple shell project)`,
You are doing a great work and that is nice work you did, let's make it nicer 💯

2023-09-11 20:23 UTC, geoffreylgv commented on sort_resource_links.py
> +    learning-material.md files.
Hello @milkiyd, we should write a 'guide' to explain this instead of let it here in the `.py` code

2023-09-11 20:23 UTC, geoffreylgv commented on sort_resource_links.py
Let's keep the name of the program simple, what do you think about `sort-resources.py`
The instruction of write by alphabetical should be added to the contributing guidelines tho, I'll manage that soon

2023-09-12 07:16 UTC, milkiyd commented
> Hi @milkiyd, did you use python code to sort automatically all links in the files? (I mean I'm seeing it, but just to confirm)

Yes it is python



> Here we have the learning resource starting by `S` but, still stay on the bottom.

It may due to the fact that the resource name is starting with a lower case 's' which have an ascii code (115) greater than the uppwercase 'W' (87). Sorry i didn't checked that before commiting.

One fix could be to make sure that all resource names start with an uppercase letter, or I could try to handle these cases directly in the code.

2023-09-12 07:18 UTC, milkiyd commented on sort_resource_links.py
Yes, i also prefer this name.
I also agree to have the instructions in a separate file (I didn't want to modify or add many files before you agree on what I were doing).

2023-09-12 09:12 UTC, geoffreylgv commented
> > Hi @milkiyd, did you use python code to sort automatically all links in the files? (I mean I'm seeing it, but just to confirm)
> 
> Yes it is python
> 
Alright, nice

> > Here we have the learning resource starting by `S` but, still stay on the bottom.
> 
> It may due to the fact that the resource name is starting with a lower case 's' which have an ascii code (115) greater than the uppwercase 'W' (87). Sorry i didn't checked that before commiting.
> 
> One fix could be to make sure that all resource names start with an uppercase letter, or I could try to handle these cases directly in the code.

No worries @milkiyd, always start with capital letter any title or sentence, but for enhancement of the code, I agree that if possible, because it'll serve you in future project I guess and sure, so you can handle if it's a lower letter or not.

2023-09-16 10:37 UTC, milkiyd commented
Hello @geoffreylgv , I updated the script according to your reviews, and added the feature to handle resources containing subsections. 
The CONTRIBUTING.md file has also been updated.

2023-09-18 23:58 UTC, geoffreylgv commented
> Hello @geoffreylgv , I updated the script according to your reviews, and added the feature to handle resources containing subsections. The CONTRIBUTING.md file has also been updated.

Hi @milkiyd, I will look into it soon, well done

2023-09-21 13:43 UTC, geoffreylgv approved these changes
Congrats Daniel, you are the big one.

`"The struggle you’re in today is developing the strengths you need tomorrow. Don’t give up" `

2023-09-21 13:43 UTC, geoffreylgv commented on CONTRIBUTING.md
> +correct paths to the resources.md and learning-material.md files.
Awesome @milkiyd, even if we will update it, it's much better

2023-09-21 13:43 UTC, geoffreylgv commented on dsa/resources/resources.md
> +- [Project Euler](https://projecteuler.net/)
Yeah, nice work here !

2023-09-21 13:43 UTC, geoffreylgv commented on sort-resources.py
Since is nice now, I'll politely merge it, thank you, @milkiyd, for the great work

2023-09-21 13:44 UTC, merged